packages:
  - 'packages/*'
  - 'apps/*'

catalog:
  typescript: ^5.4.0
  
catalogs:
  crypto:
    '@noble/ed25519': ^2.0.0
    '@noble/hashes': ^1.4.0
  db:
    'better-sqlite3': ^9.4.0
    '@types/better-sqlite3': ^7.6.9
